spring.application.name=jobx_portal

spring.datasource.url=jdbc:mysql://localhost:3306/job_portal_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Channa#99

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
